version: "3.8"

services:
  api-test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-test-runner
    ports:
      - "8080:8080"
    volumes:
      - ./allure-report:/app/target/site/allure-maven-plugin
    command: >
      sh -c "
      mvn test allure:report &&
      cp -r target/site/allure-maven-plugin/* /app/target/site/allure-maven-plugin
      "

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-server
    ports:
      - "5050:5050"
    volumes:
      - ./allure-report:/app/allure-results